#!/bin/bash
# Copyright (C) 2012 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
# Copyright (C) 2012 Colin Walters <walters@verbum.org>
# Copyright (C) 2012 Adrian Perez <aperez@igalia.com>
#
# This library is free software; you can redistribute it and/or
# modify it under the terms of the GNU Lesser General Public
# License as published by the Free Software Foundation; either
# version 2 of the License, or (at your option) any later version.
#
# This library is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
# Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public
# License along with this library; if not, write to the
# Free Software Foundation, Inc., 59 Temple Place - Suite 330,
# Boston, MA 02111-1307, USA.

set -e
umask 022

die () {
    echo "$*" 1>&2
    exit 1
}

usage () {
    echo "$0: SRCDIR BUILDDIR ARCHITECTURE REPO"
}

srcdir=$1
test -n "${srcdir}" || (usage; exit 1)
builddir=$2
test -n "${builddir}" || (usage; exit 1)
architecture=$3
test -n "${architecture}" || (usage; exit 1)
repo_path=$4
test -n "${repo_path}" || (usage; exit 1)

. "${srcdir}/oe-init-build-env" "${builddir}"

if ! grep -q meta-maui ${builddir}/conf/bblayers.conf; then
    echo "BBLAYERS += \"${srcdir}/meta-maui\"" >> ${builddir}/conf/bblayers.conf
fi

case "$architecture" in
    i686) MACHINE="atom-pc";;
    x86_64) MACHINE="qemux86-64";;
    *) echo "Error: Unhandled architecture '$architecture'"; exit 1;;
esac

mkdir -p ${builddir}/conf
localconf=${builddir}/conf/local.conf
if ! grep -q "DISTRO.*maui" ${localconf}; then
    numcpus=$(( $(getconf _NPROCESSORS_ONLN) / 2 + 1 ))
    cat > ${localconf}.tmp <<EOF
PARALLEL_MAKE = "-j ${numcpus}"
BB_NUMBER_THREADS = "${numcpus}"
LAYER_CONF_VERSION = "6"
CONF_VERSION = "1"
MACHINE = "${MACHINE}"
DISTRO = "mauidistro"
USER_CLASSES = ""
PACKAGE_CLASSES = "package_rpm"
PATCHRESOLVE = "noop"
SSTATE_DIR = "${SSTATE_DIR}"
DL_DIR = "${DL_DIR}"
INHERIT += "rm_work"
EOF
    mv ${localconf}.tmp ${localconf}
fi

IMAGEDIR=${builddir}/tmp-eglibc/deploy/images
mkdir -p "${IMAGEDIR}"
ln -sf ${repo_path} ${IMAGEDIR}/repo

bitbake maui-contents-{runtime,devel}

for basetype in runtime devel; do
    ln -sf ${builddir}/tmp-eglibc/deploy/images/maui-contents-${basetype}-${MACHINE}.tar.gz maui-contents-${basetype}-${architecture}.tar.gz
done
